### ISSUE TITLE
Research - Selenium & Webview

### ISSUE THREAD

**Issue by AndriPL** [nokia-wroclaw/innovativeproject-noticrawl#28]
https://github.com/SeleniumHQ/selenium-ide

**Comment by ghost** [comment]
FROM GOOGLE DRIVE

selenium and xpath:
[https://github.com/TheDancerCodes/Selenium-Webscraping-Example/blob/master/webscraping_example.py](url)

selenium, pandas and beautifull soup project:
[https://www.freecodecamp.org/news/better-web-scraping-in-python-with-selenium-beautiful-soup-and-pandas-d6390592e251/](url)

**Comment by AndriPL** [comment]
There is implementation of a function for highlighting elements on webpage done by uBlockOrigin:

https://github.com/gorhill/uBlock/blob/5cc7a3a8524371ce8d7ab669813b80ef09276c7f/src/js/scriptlets/element-picker.js#L228
@arehcats @conrezo

**Comment by AndriPL** [comment]
@conrezo @arehcats Did you know that there is a method that returns size of element?
https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

**Comment by arehcats** [comment]
> @conrezo @arehcats Did you know that there is a method that returns size of element?
> https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

Yes, i used that to make border on elements while mouse move, and i think i will use this to select elements by click also. Currently know how to use it and it won't be a problem

**Comment by conrezo** [comment]
iframe documentation:
https://developer.mozilla.org/pl/docs/Web/HTML/Element/iframe
